version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: wikijs-postgres
    environment:
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs_password
      POSTGRES_DB: wikidb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wikinet

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs_password
      DB_NAME: wikidb
    depends_on:
      - postgres
    networks:
      - wikinet

  nginx:
    image: nginx:latest
    container_name: wikijs-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt/live/docksrv
      - certs-data:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wikinet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt/live/docksrv
      - certs-data:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wikinet

volumes:
  postgres-data:
    driver: local
  wikijs-data:
    driver: local
  certs:
    driver: local
  certs-data:
    driver: local

networks:
  wikinet:
    driver: bridge
